In [55]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import time
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_recall_fscore_support
from sklearn.preprocessing import MinMaxScaler

In [56]:
df=pd.read_csv('synthetic_fraud_dataset.csv')

In [57]:
df.head()

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Timestamp,Account_Balance,Device_Type,Location,Merchant_Category,IP_Address_Flag,...,Daily_Transaction_Count,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Type,Card_Age,Transaction_Distance,Authentication_Method,Risk_Score,Is_Weekend,Fraud_Label
0,TXN_33553,USER_1834,39.79,POS,2023-08-14 19:30:00,93213.17,Laptop,Sydney,Travel,0,...,7,437.63,3,Amex,65,883.17,Biometric,0.8494,0,0
1,TXN_9427,USER_7875,1.19,Bank Transfer,2023-06-07 04:01:00,75725.25,Mobile,New York,Clothing,0,...,13,478.76,4,Mastercard,186,2203.36,Password,0.0959,0,1
2,TXN_199,USER_2734,28.96,Online,2023-06-20 15:25:00,1588.96,Tablet,Mumbai,Restaurants,0,...,14,50.01,4,Visa,226,1909.29,Biometric,0.8400,0,1
3,TXN_12447,USER_2617,254.32,ATM Withdrawal,2023-12-07 00:31:00,76807.20,Tablet,New York,Clothing,0,...,8,182.48,4,Visa,76,1311.86,OTP,0.7935,0,1
4,TXN_39489,USER_2014,31.28,POS,2023-11-11 23:44:00,92354.66,Mobile,Mumbai,Electronics,0,...,14,328.69,4,Mastercard,140,966.98,Password,0.3819,1,1

In [58]:
df.drop('Risk_Score', axis=1, inplace=True)

In [59]:
df.drop('Transaction_ID', axis=1, inplace=True)
df.drop('User_ID', axis=1, inplace=True)

In [60]:
df.head()

,Transaction_Amount,Transaction_Type,Timestamp,Account_Balance,Device_Type,Location,Merchant_Category,IP_Address_Flag,Previous_Fraudulent_Activity,Daily_Transaction_Count,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Type,Card_Age,Transaction_Distance,Authentication_Method,Is_Weekend,Fraud_Label
0,39.79,POS,2023-08-14 19:30:00,93213.17,Laptop,Sydney,Travel,0,0,7,437.63,3,Amex,65,883.17,Biometric,0,0
1,1.19,Bank Transfer,2023-06-07 04:01:00,75725.25,Mobile,New York,Clothing,0,0,13,478.76,4,Mastercard,186,2203.36,Password,0,1
2,28.96,Online,2023-06-20 15:25:00,1588.96,Tablet,Mumbai,Restaurants,0,0,14,50.01,4,Visa,226,1909.29,Biometric,0,1
3,254.32,ATM Withdrawal,2023-12-07 00:31:00,76807.20,Tablet,New York,Clothing,0,0,8,182.48,4,Visa,76,1311.86,OTP,0,1
4,31.28,POS,2023-11-11 23:44:00,92354.66,Mobile,Mumbai,Electronics,0,1,14,328.69,4,Mastercard,140,966.98,Password,1,1

In [61]:
df['Device_Type'].value_counts()

Device_Type
Tablet    16779
Mobile    16640
Laptop    16581
Name: count, dtype: int64

In [62]:
df['Device_Type'] = df['Device_Type'].map({'Mobile': 0, 'Laptop': 1, 'Tablet': 2})

In [63]:
df['Authentication_Method'].value_counts()

Authentication_Method
Biometric    12591
PIN          12586
Password     12457
OTP          12366
Name: count, dtype: int64

In [64]:
df['Authentication_Method'] = df['Authentication_Method'].map({'Biometric': 0,'PIN':1 ,'Password':2,'OTP': 3})

In [65]:
df.head()

,Transaction_Amount,Transaction_Type,Timestamp,Account_Balance,Device_Type,Location,Merchant_Category,IP_Address_Flag,Previous_Fraudulent_Activity,Daily_Transaction_Count,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Type,Card_Age,Transaction_Distance,Authentication_Method,Is_Weekend,Fraud_Label
0,39.79,POS,2023-08-14 19:30:00,93213.17,1,Sydney,Travel,0,0,7,437.63,3,Amex,65,883.17,0,0,0
1,1.19,Bank Transfer,2023-06-07 04:01:00,75725.25,0,New York,Clothing,0,0,13,478.76,4,Mastercard,186,2203.36,2,0,1
2,28.96,Online,2023-06-20 15:25:00,1588.96,2,Mumbai,Restaurants,0,0,14,50.01,4,Visa,226,1909.29,0,0,1
3,254.32,ATM Withdrawal,2023-12-07 00:31:00,76807.20,2,New York,Clothing,0,0,8,182.48,4,Visa,76,1311.86,3,0,1
4,31.28,POS,2023-11-11 23:44:00,92354.66,0,Mumbai,Electronics,0,1,14,328.69,4,Mastercard,140,966.98,2,1,1

In [66]:
df['Transaction_Type'].value_counts()

Transaction_Type
POS               12549
Online            12546
ATM Withdrawal    12453
Bank Transfer     12452
Name: count, dtype: int64

In [67]:
df['Transaction_Type'] = df['Transaction_Type'].map({'POS':0,'Online': 1, 'ATM Withdrawal': 2, 'Bank Transfer': 3})

In [68]:
df.head()

,Transaction_Amount,Transaction_Type,Timestamp,Account_Balance,Device_Type,Location,Merchant_Category,IP_Address_Flag,Previous_Fraudulent_Activity,Daily_Transaction_Count,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Type,Card_Age,Transaction_Distance,Authentication_Method,Is_Weekend,Fraud_Label
0,39.79,0,2023-08-14 19:30:00,93213.17,1,Sydney,Travel,0,0,7,437.63,3,Amex,65,883.17,0,0,0
1,1.19,3,2023-06-07 04:01:00,75725.25,0,New York,Clothing,0,0,13,478.76,4,Mastercard,186,2203.36,2,0,1
2,28.96,1,2023-06-20 15:25:00,1588.96,2,Mumbai,Restaurants,0,0,14,50.01,4,Visa,226,1909.29,0,0,1
3,254.32,2,2023-12-07 00:31:00,76807.20,2,New York,Clothing,0,0,8,182.48,4,Visa,76,1311.86,3,0,1
4,31.28,0,2023-11-11 23:44:00,92354.66,0,Mumbai,Electronics,0,1,14,328.69,4,Mastercard,140,966.98,2,1,1

In [69]:
df['Merchant_Category'].value_counts()

Merchant_Category
Clothing       10033
Groceries      10019
Travel         10015
Restaurants     9976
Electronics     9957
Name: count, dtype: int64

In [70]:
df=pd.concat([df,pd.get_dummies(df['Merchant_Category'],dtype=int, prefix='Merchant_Category')], axis=1)

In [71]:
df.drop('Merchant_Category', axis=1, inplace=True)
df.head()

,Transaction_Amount,Transaction_Type,Timestamp,Account_Balance,Device_Type,Location,IP_Address_Flag,Previous_Fraudulent_Activity,Daily_Transaction_Count,Avg_Transaction_Amount_7d,...,Card_Age,Transaction_Distance,Authentication_Method,Is_Weekend,Fraud_Label,Merchant_Category_Clothing,Merchant_Category_Electronics,Merchant_Category_Groceries,Merchant_Category_Restaurants,Merchant_Category_Travel
0,39.79,0,2023-08-14 19:30:00,93213.17,1,Sydney,0,0,7,437.63,...,65,883.17,0,0,0,0,0,0,0,1
1,1.19,3,2023-06-07 04:01:00,75725.25,0,New York,0,0,13,478.76,...,186,2203.36,2,0,1,1,0,0,0,0
2,28.96,1,2023-06-20 15:25:00,1588.96,2,Mumbai,0,0,14,50.01,...,226,1909.29,0,0,1,0,0,0,1,0
3,254.32,2,2023-12-07 00:31:00,76807.20,2,New York,0,0,8,182.48,...,76,1311.86,3,0,1,1,0,0,0,0
4,31.28,0,2023-11-11 23:44:00,92354.66,0,Mumbai,0,1,14,328.69,...,140,966.98,2,1,1,0,1,0,0,0

In [72]:
df['Location'].value_counts()

Location
Tokyo       10208
Mumbai       9994
London       9945
Sydney       9938
New York     9915
Name: count, dtype: int64

In [73]:
df=pd.concat([df,pd.get_dummies(df['Location'],dtype=int, prefix='Location')], axis=1)
df.drop('Location', axis=1, inplace=True)
df.head()

,Transaction_Amount,Transaction_Type,Timestamp,Account_Balance,Device_Type,IP_Address_Flag,Previous_Fraudulent_Activity,Daily_Transaction_Count,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,...,Merchant_Category_Clothing,Merchant_Category_Electronics,Merchant_Category_Groceries,Merchant_Category_Restaurants,Merchant_Category_Travel,Location_London,Location_Mumbai,Location_New York,Location_Sydney,Location_Tokyo
0,39.79,0,2023-08-14 19:30:00,93213.17,1,0,0,7,437.63,3,...,0,0,0,0,1,0,0,0,1,0
1,1.19,3,2023-06-07 04:01:00,75725.25,0,0,0,13,478.76,4,...,1,0,0,0,0,0,0,1,0,0
2,28.96,1,2023-06-20 15:25:00,1588.96,2,0,0,14,50.01,4,...,0,0,0,1,0,0,1,0,0,0
3,254.32,2,2023-12-07 00:31:00,76807.20,2,0,0,8,182.48,4,...,1,0,0,0,0,0,0,1,0,0
4,31.28,0,2023-11-11 23:44:00,92354.66,0,0,1,14,328.69,4,...,0,1,0,0,0,0,1,0,0,0

In [74]:
print(f"Maximum Daily_Transaction_Count: {df['Daily_Transaction_Count'].max()}")
print(f"Minimum Daily_Transaction_Count: {df['Daily_Transaction_Count'].min()}")

Maximum Daily_Transaction_Count: 14
Minimum Daily_Transaction_Count: 1

In [75]:
df['Daily_Transaction_Count_bin'] = pd.cut(
    df['Daily_Transaction_Count'],
    bins=[0, 5, 15, float('inf')],
    labels=[0,1,2]
).astype(int)

In [76]:
df.drop(['Daily_Transaction_Count'], axis=1, inplace=True)

In [77]:
df.head()

,Transaction_Amount,Transaction_Type,Timestamp,Account_Balance,Device_Type,IP_Address_Flag,Previous_Fraudulent_Activity,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Type,...,Merchant_Category_Electronics,Merchant_Category_Groceries,Merchant_Category_Restaurants,Merchant_Category_Travel,Location_London,Location_Mumbai,Location_New York,Location_Sydney,Location_Tokyo,Daily_Transaction_Count_bin
0,39.79,0,2023-08-14 19:30:00,93213.17,1,0,0,437.63,3,Amex,...,0,0,0,1,0,0,0,1,0,1
1,1.19,3,2023-06-07 04:01:00,75725.25,0,0,0,478.76,4,Mastercard,...,0,0,0,0,0,0,1,0,0,1
2,28.96,1,2023-06-20 15:25:00,1588.96,2,0,0,50.01,4,Visa,...,0,0,1,0,0,1,0,0,0,1
3,254.32,2,2023-12-07 00:31:00,76807.20,2,0,0,182.48,4,Visa,...,0,0,0,0,0,0,1,0,0,1
4,31.28,0,2023-11-11 23:44:00,92354.66,0,0,1,328.69,4,Mastercard,...,1,0,0,0,0,1,0,0,0,1

In [78]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'])
df['transaction_hour'] = df['Timestamp'].dt.hour

In [79]:
df['day_of_week'] = df['Timestamp'].dt.dayofweek
df['day'] = df['Timestamp'].dt.day
df['month'] = df['Timestamp'].dt.month

In [80]:
df['is_night'] = df['transaction_hour'].apply(lambda x: 1 if (x >= 18 or x <= 1) else 0)

In [81]:
df.drop('Timestamp', axis=1, inplace=True)
df.head()

,Transaction_Amount,Transaction_Type,Account_Balance,Device_Type,IP_Address_Flag,Previous_Fraudulent_Activity,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Type,Card_Age,...,Location_Mumbai,Location_New York,Location_Sydney,Location_Tokyo,Daily_Transaction_Count_bin,transaction_hour,day_of_week,day,month,is_night
0,39.79,0,93213.17,1,0,0,437.63,3,Amex,65,...,0,0,1,0,1,19,0,14,8,1
1,1.19,3,75725.25,0,0,0,478.76,4,Mastercard,186,...,0,1,0,0,1,4,2,7,6,0
2,28.96,1,1588.96,2,0,0,50.01,4,Visa,226,...,1,0,0,0,1,15,1,20,6,0
3,254.32,2,76807.20,2,0,0,182.48,4,Visa,76,...,0,1,0,0,1,0,3,7,12,1
4,31.28,0,92354.66,0,0,1,328.69,4,Mastercard,140,...,1,0,0,0,1,23,5,11,11,1

In [82]:
df['Card_Type'].value_counts()

Card_Type
Mastercard    12693
Visa          12560
Amex          12419
Discover      12328
Name: count, dtype: int64

In [83]:
df=pd.concat([df,pd.get_dummies(df['Card_Type'],dtype=int, prefix='Card_Type')], axis=1)

In [84]:
df.drop('Card_Type', axis=1, inplace=True)

In [85]:
print(f"Minimum Card Age : {df['Card_Age'].min()}")
print(f"Maximum Card Age : {df['Card_Age'].max()}")

Minimum Card Age : 1
Maximum Card Age : 239

In [86]:
df['Card_Age_bin'] = pd.cut(
    df['Card_Age'],
    bins=[0, 6, 24, 60, 240],
    labels=[0, 1, 2, 3]
).astype(int)

In [87]:
df.drop(['Card_Age'], axis=1, inplace=True)

In [88]:
df.head()

,Transaction_Amount,Transaction_Type,Account_Balance,Device_Type,IP_Address_Flag,Previous_Fraudulent_Activity,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Transaction_Distance,Authentication_Method,...,transaction_hour,day_of_week,day,month,is_night,Card_Type_Amex,Card_Type_Discover,Card_Type_Mastercard,Card_Type_Visa,Card_Age_bin
0,39.79,0,93213.17,1,0,0,437.63,3,883.17,0,...,19,0,14,8,1,1,0,0,0,3
1,1.19,3,75725.25,0,0,0,478.76,4,2203.36,2,...,4,2,7,6,0,0,0,1,0,3
2,28.96,1,1588.96,2,0,0,50.01,4,1909.29,0,...,15,1,20,6,0,0,0,0,1,3
3,254.32,2,76807.20,2,0,0,182.48,4,1311.86,3,...,0,3,7,12,1,0,0,0,1,3
4,31.28,0,92354.66,0,0,1,328.69,4,966.98,2,...,23,5,11,11,1,0,0,1,0,3

In [89]:
from sklearn.preprocessing import MinMaxScaler

# DO NOT fit on entire df - will cause data leakage!
# These will be scaled AFTER train-test split
print("Original columns preserved for proper scaling after train-test split")

Original columns preserved for proper scaling after train-test split

In [90]:
# Don't drop these yet - we'll drop them after proper scaling
# df.drop(['Transaction_Amount','Account_Balance','Avg_Transaction_Amount_7d'], axis=1, inplace=True)

In [91]:
y=df['Fraud_Label']
X=df.drop('Fraud_Label', axis=1)

In [92]:
# CRITICAL FIX: Split FIRST, then scale (prevents data leakage)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Now fit scalers on training data ONLY
scaler_amount = MinMaxScaler()
scaler_balance = MinMaxScaler()
scaler_avg = MinMaxScaler()

# Fit and transform training data
X_train['Transaction_amount_scaled'] = scaler_amount.fit_transform(X_train[['Transaction_Amount']])
X_train['Account_Balance_scaled'] = scaler_balance.fit_transform(X_train[['Account_Balance']])
X_train['Avg_Transaction_Amount_7d_scaled'] = scaler_avg.fit_transform(X_train[['Avg_Transaction_Amount_7d']])

# Apply SAME fitted scalers to test data (without fitting again)
X_test['Transaction_amount_scaled'] = scaler_amount.transform(X_test[['Transaction_Amount']])
X_test['Account_Balance_scaled'] = scaler_balance.transform(X_test[['Account_Balance']])
X_test['Avg_Transaction_Amount_7d_scaled'] = scaler_avg.transform(X_test[['Avg_Transaction_Amount_7d']])

# Now drop original unscaled columns
X_train.drop(['Transaction_Amount','Account_Balance','Avg_Transaction_Amount_7d'], axis=1, inplace=True)
X_test.drop(['Transaction_Amount','Account_Balance','Avg_Transaction_Amount_7d'], axis=1, inplace=True)

print("✓ DATA LEAKAGE FIXED")
print(f"  Scalers fit on training data ({len(X_train)} samples) only")
print(f"  Test data ({len(X_test)} samples) scaled with training statistics")

✓ DATA LEAKAGE FIXED
  Scalers fit on training data (40000 samples) only
  Test data (10000 samples) scaled with training statistics

In [93]:
from sklearn.preprocessing import StandardScaler

# Fill missing values using training data statistics ONLY
X_train_filled = X_train.fillna(X_train.mean())
X_test_filled = X_test.fillna(X_train.mean())  # Use TRAINING mean, not test mean!

# Apply StandardScaler on top of MinMaxScaler (additional normalization)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_filled)
X_test_scaled = scaler.transform(X_test_filled)  # Use FITTED scaler, don't fit on test!

In [94]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline

model1 = make_pipeline(StandardScaler(), 
                      LogisticRegression(max_iter=10000, solver='lbfgs'))
model1.fit(X_train_filled, y_train)  # model training with properly split data

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression(max_iter=10000))])

In [95]:
prediction = model1.predict(X_test_filled)  # prediction on properly held-out test set
prediction

array([0, 0, 0, ..., 0, 0, 0], shape=(10000,))

In [96]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
acc = accuracy_score(y_test, model1.predict(X_test_filled)) * 100
print(f"Logistic Regression model accuracy: {acc:.2f}%")

Logistic Regression model accuracy: 86.95%

In [97]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, prediction))
print(classification_report(y_test, prediction))

[[6694   93]
 [1212 2001]]
              precision    recall  f1-score   support

           0       0.85      0.99      0.91      6787
           1       0.96      0.62      0.75      3213

    accuracy                           0.87     10000
   macro avg       0.90      0.80      0.83     10000
weighted avg       0.88      0.87      0.86     10000

In [98]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
models = {
    'LogisticRegression': LogisticRegression(),
    'DecisionTree': DecisionTreeClassifier(),
    'RandomForest': RandomForestClassifier(),
    'KNN': KNeighborsClassifier(),
    'SVM': SVC(),  
    'NaiveBayes': GaussianNB(),

}

In [99]:
rf = RandomForestClassifier()
rf.fit(X_train_scaled, y_train)  # Uses properly scaled training data
y_pred_rf = rf.predict(X_test_scaled)  # Predicts on properly scaled test data
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))

Random Forest Accuracy: 0.8772

In [100]:
from sklearn.metrics import classification_report
classification_report_rf = classification_report(y_test, y_pred_rf)

In [101]:
print(classification_report_rf)

              precision    recall  f1-score   support

           0       0.85      1.00      0.92      6787
           1       1.00      0.62      0.76      3213

    accuracy                           0.88     10000
   macro avg       0.92      0.81      0.84     10000
weighted avg       0.90      0.88      0.87     10000